### ISSUE TITLE
Is pipe forward possibe?

### ISSUE THREAD

**Issue by Streametch** [Brijendrasial/CentMinMod_MailServer#2]
Hello!
I'm tried to add pipe to email forward - but it's doesn't work correct.
Or pipe to php  is not supported? Is it's possible to add pipe alias directly in postfix?

**Comment by Brijendrasial** [comment]
Can you paste the code what you are exactly trying to add

**Comment by Streametch** [comment]
Here is example, I try in two ways:
1. Add Forward:
Source Email: test@example.com
`Destination  Email: | php -q /home/nginx/domains/server.****.net/public/pipe --address=test@example.com`
Second try was with Destination  Email as:
`"| php -q /home/nginx/domains/server.****.net/public/pipe --address=test@example.com"`
no luck. In postfix log:
`postfix/smtp[19018]: 451A410E5D26: to=<| php -q /home/nginx/domains/server.****.net/public/pipe --address=test@example.com@server.****.net>, orig_to=<test@example.com>, relay=none, delay=0.54, delays=0.41/0.02/0.11/0, dsn=5.4.6, status=bounced (mail for server.****.net loops back to myself)`

**Comment by Brijendrasial** [comment]
Under destination email just add email address.

**Comment by Streametch** [comment]
Ok, so pipe is not supported yet, correct? It's not an issue

**Comment by Brijendrasial** [comment]
Yes only direct email address is supported.

**Comment by Streametch** [comment]
it will be good if you plan to add piping in forward.

**Comment by Brijendrasial** [comment]
Sure I will look into it
