### ISSUE TITLE
Configuration corruption after adding second domain

### ISSUE THREAD

**Issue by abyssmedia** [Brijendrasial/CentMinMod_MailServer#5]
Everything works fine after the initial installation of the mail server, but adding mailboxes for the second domain causes big problems.
I  have tested two options: Setup mail server again for the new domain and Create an Email for Non existing Domain. 
1. In both cases, your script rewrites the dovecot and postfix configs with the NEW SQL password!
2. Create an Email for Non existing Domain - reset myhostname to empty string and set incorrect postfix certificate (empty host name) 
3. Duplicate lines are added to the  master.cf file

**Comment by Brijendrasial** [comment]
Hello,

I am looking into it. will update you.

**Comment by Brijendrasial** [comment]
You can now download the script again from git. Using option 7 remove everything and then use option 1 to install everything. After that try option 3 or 4 as per your wish

**Comment by abyssmedia** [comment]
It looks like you checked
if [ "$input" = '2' ] || [ "$input" = '3' ]; then
in function create_email_account.
I have the previous revision of the script where: 
4) Add/Remove New Email or Change Password of Existing Email

I can't use the latest revision since its installed SpamAsassin and ClamAV which i don't need

**Comment by Brijendrasial** [comment]
Please provide me the script. So I can make changes there as I dont maintain old version.

**Comment by abyssmedia** [comment]
This revision: https://github.com/Brijendrasial/CentMinMod_MailServer/blob/deab4f646b0fbfa140a2c6d3603880e4fc4df31e/CMM_Email.sh
Line 216 should be 
if [ "$input" = '2' ] || [ "$input" = '4' ]; then

**Comment by Brijendrasial** [comment]
its should be 

if [ "$input" = '4' ] || [ "$input" = '5' ]; then

**Comment by Brijendrasial** [comment]
Did it solve your issue?

**Comment by abyssmedia** [comment]
Yes.

**Comment by Brijendrasial** [comment]
Great I am closing this issue then
